package llm

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/borch-ai/powerword/pkg/config"
	"github.com/borch-ai/powerword/pkg/telemetry"
)

// Role defines the role of the message sender.
type Role string

const (
	RoleSystem    Role = "system"
	RoleUser      Role = "user"
	RoleAssistant Role = "assistant"
	RoleTool      Role = "tool"
)

// ToolCall represents a call to a tool generated by the model.
type ToolCall struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Arguments string `json:"arguments"` // JSON string representation of tool parameters
}

// TokenUsage represents the token usage for a single request.
type TokenUsage = telemetry.TokenUsage

// Message represents a single message in the chat history.
type Message struct {
	Role    Role   `json:"role"`
	Content string `json:"content"`
	// ToolCalls is set if the message is from the assistant and requests tool execution.
	ToolCalls []ToolCall `json:"tool_calls,omitempty"`
	// ToolCallID links this tool message back to the tool call request.
	// Only set when Role is RoleTool.
	ToolCallID string `json:"tool_call_id,omitempty"`
	// Usage may be populated if token usage is available from the provider.
	Usage *TokenUsage `json:"usage,omitempty"`
}

// ToolDefinition defines a tool that can be called by the model.
type ToolDefinition struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	// InputSchema is a JSON Schema defining the input parameters.
	// Typically represented as a map[string]any or structured JSON schema object.
	InputSchema any `json:"input_schema"`
}

// StreamChunk represents a chunk of data returned from a streaming API call.
type StreamChunk struct {
	Content string
	Error   error
	// Usage may be populated on chunks that report token usage (e.g. at the start or end of the stream).
	Usage *TokenUsage
}

// GenerateOption is a functional option for configuring a generation request.
type GenerateOption func(*generateOptions)

type generateOptions struct {
	ResponseMIMEType string
}

// WithResponseMIMEType sets the expected MIME type of the generated response (e.g. "application/json").
func WithResponseMIMEType(mimeType string) GenerateOption {
	return func(o *generateOptions) {
		o.ResponseMIMEType = mimeType
	}
}

// LLMClient is the uniform interface for LLM providers.
type LLMClient interface {
	Generate(ctx context.Context, messages []Message, tools []ToolDefinition, opts ...GenerateOption) (*Message, error)
	Stream(ctx context.Context, messages []Message, tools []ToolDefinition) (<-chan StreamChunk, error)
	ListModels(ctx context.Context) ([]string, error)
}

// NewClient returns an LLMClient instance based on the configuration.
func NewClient(cfg *config.Config) (LLMClient, error) {
	if cfg == nil {
		return nil, errors.New("config is nil")
	}

	model := strings.ToLower(cfg.Model)
	if strings.Contains(model, "gemini") {
		if cfg.APIKeys.Gemini == "" {
			return nil, errors.New("gemini API key is not configured")
		}
		return NewGeminiClient(cfg.APIKeys.Gemini, cfg.Model)
	}

	if strings.Contains(model, "claude") {
		if cfg.APIKeys.Anthropic == "" {
			return nil, errors.New("anthropic API key is not configured")
		}
		return NewAnthropicClient(cfg.APIKeys.Anthropic, cfg.Model)
	}

	// Fallback/default to OpenAI
	if cfg.APIKeys.OpenAI == "" {
		return nil, errors.New("openai API key is not configured")
	}
	return NewOpenAIClient(cfg.APIKeys.OpenAI, cfg.Model)
}

// NewCriticClient returns an LLMClient tailored for the critic, using critic-specific configs if provided.
func NewCriticClient(cfg *config.Config) (LLMClient, error) {
	if cfg == nil {
		return nil, errors.New("config is nil")
	}

	if cfg.CriticProvider == "" {
		// Fallback to the main client if no critic-specific provider is set.
		return NewClient(cfg)
	}

	model := cfg.CriticModel
	if model == "" {
		model = cfg.Model
	}
	provider := strings.ToLower(cfg.CriticProvider)

	if strings.Contains(provider, "openai") || strings.Contains(provider, "ollama") {
		// OpenAI compatible provider
		apiKey := cfg.APIKeys.OpenAI
		if apiKey == "" {
			apiKey = "dummy" // local models like Ollama might not require a real key
		}

		return NewCustomOpenAIClient(apiKey, model, cfg.CriticEndpoint)
	}

	if strings.Contains(provider, "gemini") {
		if cfg.APIKeys.Gemini == "" {
			return nil, errors.New("gemini API key is not configured for critic")
		}
		return NewGeminiClient(cfg.APIKeys.Gemini, model)
	}

	if strings.Contains(provider, "claude") || strings.Contains(provider, "anthropic") {
		if cfg.APIKeys.Anthropic == "" {
			return nil, errors.New("anthropic API key is not configured for critic")
		}
		return NewAnthropicClient(cfg.APIKeys.Anthropic, model)
	}

	return nil, fmt.Errorf("unsupported critic provider: %s", provider)
}
