package main

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log"

	"powerword/internal/config"
	"powerword/internal/remote"
	"powerword/internal/review"

	"github.com/spf13/cobra"
)

func generateTunnelID() (string, error) {
	b := make([]byte, 3)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("failed to generate tunnel ID: %w", err)
	}
	return hex.EncodeToString(b), nil
}

func newRunCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "run [prompt]",
		Short: "Run the agent with a prompt or in autonomous mode",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg := config.Active
			if cfg == nil {
				return fmt.Errorf("configuration not loaded")
			}

			daemonFlag, _ := cmd.Flags().GetBool("daemon")
			if daemonFlag || cfg.Daemon {
				broker, err := remote.NewFirebaseBroker(cmd.Context(), cfg.FirebaseProject)
				if err != nil {
					return fmt.Errorf("failed to init firebase broker: %w", err)
				}
				tunnelID, err := generateTunnelID()
				if err != nil {
					return err
				}
				log.Printf("Starting remote daemon mode. Tunnel ID: %s", tunnelID)
				log.Printf("Waiting for dashboard connection...")

				// TODO(task-6.2): Replace with actual local SDP offer generated by the WebRTC layer
				mockOffer := "mock-sdp-offer-from-daemon"
				answer, err := broker.ExchangeSDP(cmd.Context(), tunnelID, mockOffer)
				if err != nil {
					return fmt.Errorf("sdp exchange failed: %w", err)
				}
				log.Printf("Successfully received SDP answer from dashboard (length: %d)", len(answer))
				log.Printf("Daemon mode WebRTC signaling complete!")
				return nil
			}

			prompt := ""
			if len(args) > 0 {
				prompt = args[0]
			}

			if cfg.Autonomous {
				return review.RunAutonomousLoop(cmd.Context(), cfg)
			}

			if config.Runner == nil {
				return fmt.Errorf("no execution runner registered")
			}
			return config.Runner(cmd.Context(), cfg, prompt)
		},
	}

	cmd.Flags().Bool("daemon", false, "Start in remote daemon mode")
	return cmd
}
