name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run Linter
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12.2

  pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      statuses: write
      pull-requests: read
    steps:
      - name: Semantic PR Check
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert

  security-and-test:
    name: Security & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run Vulnerability Scan
        run: make vuln

      - name: Run Tests & Check Coverage
        run: make check-coverage

      - name: Compile Binaries
        run: make build
