name: Lint Markdown

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.jsonc'

permissions:
  contents: read

jobs:
  lint:
    uses: borch-ai/.github/.github/workflows/markdown-lint.yml@v0.2.2
