name: PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  statuses: write
  pull-requests: read
  contents: read

jobs:
  check:
    uses: borch-ai/.github/.github/workflows/pr-title.yml@main
    secrets: inherit
